KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="broker"
    password="brokerpw"
    user_broker="brokerpw"
    user_tenantA="tenantApw"
    user_tenantB="tenantBpw";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="broker"
    password="brokerpw";
};
